import { sql } from '@payloadcms/db-sqlite/drizzle'
import type { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-sqlite'

/**
 * Phase 4.56 — tambah kolom `entry_speed` (text, default 'normal') dan
 * `entry_dur_ms` (numeric, default 900) di semua 208 tabel block
 * yang punya `entry_animation`. Menghindari SQLite recreate-table pattern
 * — pakai ADD COLUMN langsung karena kedua kolom text/numeric dgn default.
 *
 * Total ALTER statements: 414.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`accommodations_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_trust_badges\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_trust_badges\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_testimonials_carousel\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_testimonials_carousel\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_trust_badges\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_trust_badges\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_value_props_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_value_props_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_testimonials_carousel\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_testimonials_carousel\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_trust_badges\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_trust_badges\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_value_props_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_value_props_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_testimonials_carousel\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_testimonials_carousel\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_trust_badges\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_trust_badges\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_value_props_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_value_props_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_trust_badges\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_trust_badges\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_testimonials_carousel\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_testimonials_carousel\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_trust_badges\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_trust_badges\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_value_props_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_value_props_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_testimonials_carousel\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_testimonials_carousel\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_trust_badges\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_trust_badges\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_value_props_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_value_props_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_testimonials_carousel\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_testimonials_carousel\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_trust_badges\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_trust_badges\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_value_props_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_value_props_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_category_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_category_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_contact\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_contact\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_cta\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_cta\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_embed\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_embed\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_faq\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_faq\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_featured_post\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_featured_post\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_gallery\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_gallery\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_hero\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_hero\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_image\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_image\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_newsletter\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_newsletter\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_popular_posts\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_popular_posts\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_post_list\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_post_list\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_rich_text\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_rich_text\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_grid\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_grid\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_stats_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_stats_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_testimonials\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_testimonials\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_testimonials_carousel\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_testimonials_carousel\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_trust_badges\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_trust_badges\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_value_props_banner\` ADD \`entry_speed\` text DEFAULT 'normal';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_value_props_banner\` ADD \`entry_dur_ms\` numeric DEFAULT 900;`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`accommodations_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_trust_badges\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`accommodations_blocks_trust_badges\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_testimonials_carousel\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_testimonials_carousel\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_trust_badges\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_trust_badges\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_value_props_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_value_props_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_testimonials_carousel\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_testimonials_carousel\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_trust_badges\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_trust_badges\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_value_props_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_value_props_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_testimonials_carousel\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_testimonials_carousel\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_trust_badges\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_trust_badges\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_value_props_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_value_props_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_trust_badges\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_trust_badges\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_testimonials_carousel\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_testimonials_carousel\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_trust_badges\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_trust_badges\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_value_props_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_value_props_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_testimonials_carousel\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_testimonials_carousel\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_trust_badges\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_trust_badges\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_value_props_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_value_props_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_testimonials_carousel\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_testimonials_carousel\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_trust_badges\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_trust_badges\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_value_props_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_value_props_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`water_activities_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_category_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_category_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_contact\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_contact\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_cta\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_cta\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_embed\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_embed\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_faq\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_faq\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_featured_post\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_featured_post\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_gallery\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_gallery\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_hero\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_hero\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_image\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_image\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_newsletter\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_newsletter\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_popular_posts\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_popular_posts\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_post_list\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_post_list\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_rich_text\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_rich_text\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_grid\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_grid\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_stats_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_stats_banner\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_testimonials\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_testimonials\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_testimonials_carousel\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_testimonials_carousel\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_trust_badges\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_trust_badges\` DROP COLUMN \`entry_dur_ms\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_value_props_banner\` DROP COLUMN \`entry_speed\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_value_props_banner\` DROP COLUMN \`entry_dur_ms\`;`)
}
