import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_enable_round_trip\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_enable_infant\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_max_adults\` numeric DEFAULT 9;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_max_children\` numeric DEFAULT 6;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_max_infants\` numeric DEFAULT 2;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_location_type\` text DEFAULT 'ferry-port';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_starting_point_label\` text DEFAULT 'Starting Point';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_destination_label\` text DEFAULT 'Destination';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_submit_button_text\` text DEFAULT 'Update';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` ADD \`ticket_default_sort\` text DEFAULT 'earliest';`)
  await db.run(sql`ALTER TABLE \`locations\` ADD \`location_type\` text DEFAULT 'ferry-port';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_enable_round_trip\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_enable_infant\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_max_adults\` numeric DEFAULT 9;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_max_children\` numeric DEFAULT 6;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_max_infants\` numeric DEFAULT 2;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_location_type\` text DEFAULT 'ferry-port';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_starting_point_label\` text DEFAULT 'Starting Point';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_destination_label\` text DEFAULT 'Destination';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_submit_button_text\` text DEFAULT 'Update';`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` ADD \`ticket_default_sort\` text DEFAULT 'earliest';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_enable_round_trip\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_enable_infant\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_max_adults\` numeric DEFAULT 9;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_max_children\` numeric DEFAULT 6;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_max_infants\` numeric DEFAULT 2;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_location_type\` text DEFAULT 'ferry-port';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_starting_point_label\` text DEFAULT 'Starting Point';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_destination_label\` text DEFAULT 'Destination';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_submit_button_text\` text DEFAULT 'Update';`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` ADD \`ticket_default_sort\` text DEFAULT 'earliest';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_enable_round_trip\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_enable_infant\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_max_adults\` numeric DEFAULT 9;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_max_children\` numeric DEFAULT 6;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_max_infants\` numeric DEFAULT 2;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_location_type\` text DEFAULT 'ferry-port';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_starting_point_label\` text DEFAULT 'Starting Point';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_destination_label\` text DEFAULT 'Destination';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_submit_button_text\` text DEFAULT 'Update';`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` ADD \`ticket_default_sort\` text DEFAULT 'earliest';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_enable_round_trip\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_enable_infant\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_max_adults\` numeric DEFAULT 9;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_max_children\` numeric DEFAULT 6;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_max_infants\` numeric DEFAULT 2;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_location_type\` text DEFAULT 'ferry-port';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_starting_point_label\` text DEFAULT 'Starting Point';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_destination_label\` text DEFAULT 'Destination';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_submit_button_text\` text DEFAULT 'Update';`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` ADD \`ticket_default_sort\` text DEFAULT 'earliest';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_enable_round_trip\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_enable_infant\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_max_adults\` numeric DEFAULT 9;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_max_children\` numeric DEFAULT 6;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_max_infants\` numeric DEFAULT 2;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_location_type\` text DEFAULT 'ferry-port';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_starting_point_label\` text DEFAULT 'Starting Point';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_destination_label\` text DEFAULT 'Destination';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_submit_button_text\` text DEFAULT 'Update';`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` ADD \`ticket_default_sort\` text DEFAULT 'earliest';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_enable_round_trip\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_enable_infant\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_max_adults\` numeric DEFAULT 9;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_max_children\` numeric DEFAULT 6;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_max_infants\` numeric DEFAULT 2;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_location_type\` text DEFAULT 'ferry-port';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_starting_point_label\` text DEFAULT 'Starting Point';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_destination_label\` text DEFAULT 'Destination';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_submit_button_text\` text DEFAULT 'Update';`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` ADD \`ticket_default_sort\` text DEFAULT 'earliest';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_enable_round_trip\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_enable_infant\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_max_adults\` numeric DEFAULT 9;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_max_children\` numeric DEFAULT 6;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_max_infants\` numeric DEFAULT 2;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_location_type\` text DEFAULT 'ferry-port';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_starting_point_label\` text DEFAULT 'Starting Point';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_destination_label\` text DEFAULT 'Destination';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_submit_button_text\` text DEFAULT 'Update';`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` ADD \`ticket_default_sort\` text DEFAULT 'earliest';`)
  await db.run(sql`ALTER TABLE \`ferry_tickets\` ADD \`duration_minutes\` numeric;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_enable_round_trip\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_enable_infant\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_max_adults\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_max_children\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_max_infants\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_location_type\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_starting_point_label\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_destination_label\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_service_listing\` DROP COLUMN \`ticket_default_sort\`;`)
  await db.run(sql`ALTER TABLE \`locations\` DROP COLUMN \`location_type\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_enable_round_trip\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_enable_infant\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_max_adults\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_max_children\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_max_infants\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_location_type\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_starting_point_label\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_destination_label\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_service_listing\` DROP COLUMN \`ticket_default_sort\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_enable_round_trip\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_enable_infant\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_max_adults\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_max_children\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_max_infants\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_location_type\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_starting_point_label\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_destination_label\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`tours_blocks_service_listing\` DROP COLUMN \`ticket_default_sort\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_enable_round_trip\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_enable_infant\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_max_adults\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_max_children\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_max_infants\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_location_type\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_starting_point_label\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_destination_label\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`yachts_blocks_service_listing\` DROP COLUMN \`ticket_default_sort\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_enable_round_trip\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_enable_infant\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_max_adults\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_max_children\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_max_infants\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_location_type\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_starting_point_label\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_destination_label\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`restaurants_blocks_service_listing\` DROP COLUMN \`ticket_default_sort\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_enable_round_trip\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_enable_infant\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_max_adults\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_max_children\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_max_infants\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_location_type\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_starting_point_label\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_destination_label\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`venues_blocks_service_listing\` DROP COLUMN \`ticket_default_sort\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_enable_round_trip\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_enable_infant\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_max_adults\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_max_children\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_max_infants\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_location_type\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_starting_point_label\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_destination_label\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`rentals_blocks_service_listing\` DROP COLUMN \`ticket_default_sort\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_enable_round_trip\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_enable_infant\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_max_adults\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_max_children\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_max_infants\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_location_type\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_starting_point_label\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_destination_label\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_submit_button_text\`;`)
  await db.run(sql`ALTER TABLE \`spa_blocks_service_listing\` DROP COLUMN \`ticket_default_sort\`;`)
  await db.run(sql`ALTER TABLE \`ferry_tickets\` DROP COLUMN \`duration_minutes\`;`)
}
